import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { Resend } from "resend";

export async function POST(
  _request: Request,
  { params }: { params: { id: string } }
) {
  const supabase = createRouteHandlerClient({ cookies });
  const { data: { session } } = await supabase.auth.getSession();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const userId = session.user.id;

  const resend = new Resend(process.env.RESEND_API_KEY);
  const invoiceId = params.id;

  // Fetch the invoice (scoped to this user)
  const { data: invoice, error: invoiceError } = await supabase
    .from("invoices")
    .select("*")
    .eq("id", invoiceId)
    .eq("user_id", userId)
    .single();

  if (invoiceError || !invoice) {
    return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
  }

  // Fetch the client
  const { data: client, error: clientError } = await supabase
    .from("clients")
    .select("*")
    .eq("id", invoice.client_id)
    .eq("user_id", userId)
    .single();

  if (clientError || !client) {
    return NextResponse.json({ error: "Client not found" }, { status: 404 });
  }

  if (!client.email) {
    return NextResponse.json(
      { error: "Client has no email address" },
      { status: 422 }
    );
  }

  // Fetch therapist name from profiles
  const { data: profile } = await supabase
    .from("profiles")
    .select("first_name")
    .eq("user_id", userId)
    .single();

  const therapistName = profile?.first_name ?? "Your therapist";

  const sessionRate =
    invoice.visit_count > 0
      ? (invoice.amount / invoice.visit_count).toFixed(2)
      : "0.00";

  const { error: emailError } = await resend.emails.send({
    from: "GoPublic <onboarding@resend.dev>",
    to: client.email,
    subject: `Invoice from ${therapistName} — ${invoice.month}`,
    html: `
      <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; color: #111;">
        <p>Hi ${client.name},</p>
        <p>Here is your invoice for ${invoice.month}.</p>
        <p>${invoice.visit_count} session(s) × €${sessionRate} = €${invoice.amount.toFixed(2)}</p>
        <p>Please transfer to ${therapistName}. Thank you.</p>
        <p style="color: #999; font-size: 12px; margin-top: 32px;">Generated by GoPublic</p>
      </div>
    `,
  });

  if (emailError) {
    return NextResponse.json(
      { error: "Failed to send email" },
      { status: 500 }
    );
  }

  // Mark invoice as sent
  const { data: updated, error: updateError } = await supabase
    .from("invoices")
    .update({ status: "sent", sent_at: new Date().toISOString() })
    .eq("id", invoiceId)
    .eq("user_id", userId)
    .select()
    .single();

  if (updateError) {
    return NextResponse.json(
      { error: "Email sent but failed to update invoice status" },
      { status: 500 }
    );
  }

  return NextResponse.json(updated);
}
